before_script:
  - gem install --no-document nokogiri test-unit test-unit-notify rubygems-tasks yard rake simplecov

test:3.0:
  image: ruby:3.0
  script:
    - rake test

test:3.1:
  image: ruby:3.1
  script:
    - rake test

test:3.2:
  image: ruby:3.2
  script:
    - rake test

test:3.3:
  image: ruby:3.3
  script:
    - rake test

test:3.4:
  image: ruby:3.4
  script:
    - rake test
