before_script:
  - gem install --no-document nokogiri test-unit test-unit-notify rubygems-tasks yard rake pry simplecov

test:2.2:
  image: ruby:2.2
  script:
    - rake test

test:2.3:
  image: ruby:2.3
  script:
    - rake test

test:2.4:
  image: ruby:2.4
  script:
    - rake test
