before_script:
  - gem install --no-document nokogiri test-unit test-unit-notify rubygems-tasks yard rake pry simplecov

test:2.4:
  image: ruby:2.4
  script:
    - rake test

test:2.5:
  image: ruby:2.5
  script:
    - rake test

test:2.6:
  image: ruby:2.6
  script:
    - rake test
